### PR TITLE
Adds the "mapNotificationTokens" hook

### PR DESCRIPTION
**Pull request by Loilo**
Adds the `mapNotificationTokens` hook to make independent token manipulation possible as suggested in #105.
Includes duplicate of #104, that can be ignored.

### CODE REVIEW

**Comment by Toflar** [comment]
Excuse me but I don't see what this hook should provide in addition to the already present hook?

**Comment by Loilo** [comment]
It's as I described in #105: The existing hook only allows changing the tokens if the $arrTokens parameter is received by-reference.

This generally works fine but it does not restrict the changes to the current notification step but also changes the tokens for all other possible steps of the notification.
The example of the attached readme demonstrates the problem: I might want to change tokens just for the CSV export of a notification (e.g. for escaping purposes) but the current state of the present hook does not allow that.

An alternative way of course (which I unfortunately didn't come up with earlier) would be to change the architecture in a way that a fresh copy of $arrTokens would be injected into each step of a notification.

**Comment by Loilo** [comment]
As opposed to that, the `mapNotificationTokens` does not modify existing data and returns a new copy of the token's array with the modifications.

The issue could certainly be solved by changing the existing hook to expect a modified array as a return value and would only stop executing the notification if a falsy value is returned but that would break backwards compability and does therefore not sound like a wise idea.

**Comment by Toflar** [comment]
Hm. I feel like an additional hook is wrong because it does not solve the issue.
What you want would be something like this, right?

```diff
diff --git a/library/NotificationCenter/Model/Message.php b/library/NotificationCenter/Model/Message.php
index 13dcc3c..a3f9380 100644
--- a/library/NotificationCenter/Model/Message.php
+++ b/library/NotificationCenter/Model/Message.php
@@ -41,9 +41,14 @@ class Message extends \Model
             return false;
         }
 
+        // Make sure the tokens and language can be changed for one message only
+        // (by reference affects subsequent messages)
+        $cpTokens   = $arrTokens;
+        $cpLanguage = $strLanguage;
+
         if (isset($GLOBALS['TL_HOOKS']['sendNotificationMessage']) && is_array($GLOBALS['TL_HOOKS']['sendNotificationMessage'])) {
             foreach ($GLOBALS['TL_HOOKS']['sendNotificationMessage'] as $arrCallback) {
-                $blnSuccess = \System::importStatic($arrCallback[0])->{$arrCallback[1]}($this, $arrTokens, $strLanguage, $objGatewayModel);
+                $blnSuccess = \System::importStatic($arrCallback[0])->{$arrCallback[1]}($this, $cpTokens, $cpLanguage, $objGatewayModel);
 
                 if (!$blnSuccess) {
                     return false;
@@ -51,7 +56,7 @@ class Message extends \Model
             }
         }
 
-        return $objGatewayModel->getGateway()->send($this, $arrTokens, $strLanguage);
+        return $objGatewayModel->getGateway()->send($this, $cpTokens, $cpLanguage);
     }
 
     /**
```

**Comment by Loilo** [comment]
Exactly. As I said, I didn't come up with that much cleaner solution earlier. 👍

**Comment by Toflar** [comment]
Can you please test my code and report back if it works for you?

**Comment by Loilo** [comment]
Works like a charm. 👌

**Comment by Toflar** [comment]
Kk, thx. Fixed in https://github.com/terminal42/contao-notification_center/commit/4c3d3a7b9065d8989d96c91fdc1ab61e0e0bdd7c.

**Comment by Loilo** [comment]
May I ask when this is currently supposed to go to the extension repository? :)

**Comment by Toflar** [comment]
Done.

**Pull request closed without merging**
