### PR TITLE
Update ModuleNewsletterActivateNotificationCenter.php

### PR DESCRIPTION
**Pull request by Ernestopheles**
solves the issue that activating a subscription did not update tl_member.newsletter.

### CODE REVIEW

**Comment by Ernestopheles** [comment]
Maybe many did not even notice that issue. But if you want to work with tl_member.newsletter you will need to have this issue solved.
I tested the module for FE-user. I did not test it for non-FE user (that is users who are not logged in).

Attached please find a screenshot of the well working modules (I changed the template to show only possible entries).
 
Bildschirmfoto von 2020-06-27 13-16-42

**Comment by richardhj** [comment]
Hi @Ernestopheles, thanks for your PRs.

With #216 and #217, you made sure, that `tl_member.newsletter` will be updated post-newsletter-subscribe and post-newsletter-unsubscribe.
Thus, you added `$objMember->newsletter = serialize($channels);` to both modules.

However, this code is not present in the modules of the Contao Core! As a consequence, we have to find the underlying problem.

From what I can see, `tl_member.newsletter` is set in the `tl_member.onload_callback`, see here: https://github.com/contao/contao/blob/1bfa560b95d8d6e5402e9d8c5cc0575cec1c6e34/newsletter-bundle/src/Resources/contao/classes/Newsletter.php#L860.
When you open the member in the back end, the newsletter channels should be correct anyway.

Can you point out the actual problem?

**Comment by Ernestopheles** [comment]
Hi,

<<When you open the member in the back end, the newsletter channels
should be correct anyway.>> thats right, but no solution...

In my installation my changes do work fine, I cannot see what's Your
problem?

best regards,
Ernestopheles

Am Montag, den 07.09.2020, 09:29 -0700 schrieb Richard Henkenjohann:

**Comment by richardhj** [comment]
It may work fine, but it also might be not necessary :) What is the actual problem you want to solve?
I cannot see, why `tl_member.newsletters` has to be updated in these modules (and if so, we should add the changes to the Contao core as well).

**Comment by Ernestopheles** [comment]
Well, there is an inconsistency, isn't it?


Am Montag, den 07.09.2020, 13:32 -0700 schrieb Richard Henkenjohann:

**Comment by richardhj** [comment]
`tl_member.newsletter` may not be up-to-date with the data in `tl_newsletter_recipient`.
There may be an inconsistency, correct. But this does not affect, which newsletters are sent out.

However, there is no inconsistency between the notification center and the Contao core. The notification center only "mirrors" the Contao core functionality.

However, we can report an issue to contao/contao. WDYT @aschempp?

**Comment by richardhj** [comment]
Please report the issue to contao/contao when the issue can be reproduced with the Core module as well :-)

**Pull request closed without merging**
