### PR TITLE
Implemented option to append to an exisiting file

### PR DESCRIPTION
**Pull request by Toflar**
This is a PR for https://github.com/terminal42/contao-notification_center/issues/56.
@qzminski and @aschempp, please review.

### CODE REVIEW

**Comment by qzminski** [comment]
Looks good

**Comment by aschempp** [comment]
Can you explain why you changed the checkbox to a dropdown? What are the three different states? Create a new file, overwrite, or append? A blank option seems allowed, but I don't know what it would do?

**Comment by Toflar** [comment]
> A blank option seems allowed, but I don't know what it would do?

It would neither override, nor append = create a new file every time you submit the notification :)

**Comment by aschempp** [comment]
That's not really clear with the selection, is it? Maybe we should add a blank option label?

**Comment by Toflar** [comment]
Well it wasn't there until now either. I could have added another checkbox to define if it should append but then you can check not check "override" and check "append" which totally makes no sense^^ But yeah, we could provide a blank option label.

**Comment by aschempp** [comment]
Either that or include a third option and make the field mandatory (which would be better with the class constants). The current implementation is taken from the Contao file upload field, but that does not support appending so we need to find something new.

**Comment by Toflar** [comment]
I have updated the PR :)

**Comment by aschempp** [comment]
:+1:

**Pull request merged**
