### PR TITLE
Add support for images embedded in HTML

### PR DESCRIPTION
**Pull request by Toflar**
See https://github.com/terminal42/contao-notification_center/issues/319.

### CODE REVIEW

**Comment by contaoacademy** [comment]
I have tested the branch.

It worked correctly with a PNG image.

When I used an SVG image, nothing was displayed. But this could also be due to the gmail-client. I have not checked this any further.

screen-20240919_U1vhzWby

**Comment by contaoacademy** [comment]
Here is the source code for an SVG graphic

screen-20240919_QpZv9Edi

**Comment by Toflar** [comment]
That's because we don't extract `.svg` files. You can test by adding it to the regex here: https://github.com/terminal42/contao-notification_center/pull/361/files#diff-abca0b3ebb3a76489fc7f2aae9712cf66d30f6248f9983717321a84ab3f250d6R337 (e.g. by turning `png|gif|bmp` into `png|gif|svg|bmp`).

But I have no clue if that is supported by mail clients.

**Comment by fritzmg** [comment]
A quick Google search [says no](https://stackoverflow.com/a/37779566/374996).

**Comment by contaoacademy** [comment]
Are further tests necessary? SVG makes no sense as Fritz writes. So I would consider the feature ok.

**Pull request merged**
