### PR TITLE
Fix route loading in Contao 4.13

### PR DESCRIPTION
**Pull request by aschempp**
To stay compatible with Contao 4.13/Symfony 5, you cannot use attributes for route loading (since they were added in Symfony 6). But the annotation still works in Symfony 6 and 7.

### CODE REVIEW

**Review by fritzmg — COMMENTED** [review]
> But the annotation still works in Symfony 6 and 7.

It won't work in Symfony 7, will it?

**Comment by aschempp** [comment]
It will: https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/Routing/Annotation/Route.php#L14

**Comment by fritzmg** [comment]
Have you confirmed this works locally? It does not work for me in Contao 5.4 with Symfony 7.

**Review by fritzmg — CHANGES_REQUESTED** [review]
This this PR the following error occurs under Contao 5.4 with Symfony 7:

```
bin/console debug:router nc_bulky_item_download
13:02:49 CRITICAL  [console] Error thrown while running command "debug:router nc_bulky_item_download". Message: "The route "nc_bulky_item_download" does not exist."
```

**Comment by fritzmg** [comment]
> It will: https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/Routing/Annotation/Route.php#L14

As far as I can see this is just there to re-use the FQCN of the old `@Route` annotation for the attribute.

**Comment by aschempp** [comment]
Fixed in 80b942db11fe93749a778fbcebcf80adcabfbb50

**Comment by fritzmg** [comment]
This made me realize I had the same issue in `inspiredminds/contao-event-registration` and fixed it there [accordingly](https://github.com/inspiredminds/contao-event-registration/commit/ff3edd86d9ba9cf6a2100fb817d092a75e4aee6f) 😁

**Pull request merged**
