### PR TITLE
Decode HTML entities before validating tokens

### LINKED ISSUE #239: Error saving mailtemplates with if queries + module variables
Hi,

actually i found a problem that i cannot save mailtemplates anymore which contain variables from contao event subscriptions (https://github.com/codefog/contao-events_subscriptions) in combination with if query.

Contao is sending existing mailtemplates correctly but i cannot edit them anymore.

`{if event_startTime!=""}Uhrzeit: ##event_startTime##{endif}{if event_endTime!=""} - ##event_endTime## Uhr{endif}`
"Unexpected character "#" around position 17 for expression event_startTime!=""."

`{if subscription_username!=""}`
Unexpected character "#" around position 23 for expression subscription_username!="".

Variables without if query, e.g. ##subscription_firstname##, ##event_title## do not have this problem.

Bildschirmfoto 2021-08-25 um 10 22 13

I´m using the latest versions from all modules:
Contao: 4.11.9
NC: 1.5.18
Event Subscriptions: 2.12.13

### PR DESCRIPTION
**Pull request by aschempp**
fixes #239

### CODE REVIEW

**Comment by aschempp** [comment]
But I wonder why the equal signs are encoded if the field is set to `decodeEntities = true`?

**Comment by fritzmg** [comment]
> But I wonder why the equal signs are encoded if the field is set to `decodeEntities = true`?

They shouldn't in `4.9.x-dev`, should they @ausi ?

**Comment by ausi** [comment]
> > But I wonder why the equal signs are encoded if the field is set to `decodeEntities = true`?
> 
> They shouldn't in `4.9.x-dev`, should they @ausi ?

If you enable allowHtml, equal signs get encoded except valid ones from HTML attributes. Without allowHtml they should not get encoded.

**Comment by aschempp** [comment]
> If you enable allowHtml, equal signs get encoded except valid ones from HTML attributes. Without allowHtml they should not get encoded.

Which is intended in this case, since this is a tinyMCE field where we need simple tokens:
https://github.com/terminal42/contao-notification_center/blob/main/dca/tl_nc_language.php#L288

**Comment by contaoacademy** [comment]
I have also this problem. Can you release this fix?

**Pull request merged**
